language: rust
jobs:
  include:
    - env:
      - PROJECT=firmware
      - BOARD="-flightcontroller"
      - TARGET=thumbv7em-none-eabihf
    - env:
      - PROJECT=remote
      - BOARD=""
      - TARGET=""
before_script:
  - |
    sudo apt-get install libudev-dev
script:
  - |
    cd software/$PROJECT
    [ -n "$TARGET" ] && rustup target add $TARGET
    cargo build$BOARD --release
