language: rust
jobs:
  include:
    - env:
      - PROJECT=firmware
      - BOARD=flightcontroller
      - TARGET=thumbv7em-none-eabihf
script:
  - |
    cd software/$PROJECT
    rustup target add $TARGET
    cargo build-$BOARD --release
