language: rust
jobs:
  include:
    - env:
      - PROJECT=firmware
      - BOARD=bluepill
      - TARGET=thumbv7m-none-eabi
    - env:
      - PROJECT=firmware
      - BOARD=blackpill
      - TARGET=thumbv7em-none-eabihf
script:
  - |
    cd software/$PROJECT
    rustup target add $TARGET
    cargo build-$BOARD --release

