language: rust
jobs:
  include:
    - env:
      - BOARD=bluepill
      - TARGET=thumbv7m-none-eabi
script:
  - |
    cd software/firmware
    rustup target add $TARGET
    cargo build-$BOARD --release

