language: rust
jobs:
  include:
    - env:
      - PROJECT=firmware
      - BOARD=flightcontroller
      - TARGET=thumbv7em-none-eabihf
script:
  - |
    # build flightcontroller
    cd software/$PROJECT
    rustup target add $TARGET
    cargo build-$BOARD --release
    cd ..

    # build remote control
    cd remote
    cargo build --release
