name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  firmware:
    runs-on: ubuntu-latest
    env:
      TARGET: thumbv7em-none-eabihf
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        rustup target add $TARGET
        cargo build-flightcontroller --verbose
